config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :follows
  get 'main',to:"main#main"
  post 'login',to:"main#login"
  get 'logout',to:"main#logout"
  get 'register',to:"main#register"
  post 'register',to:"main#register_create"
  get 'feed',to:"main#feed"
  get 'create_post', to:"main#create_post"
  post 'create_new_post', to:"main#create_new_post"
  get 'profile/:name', to:'main#profile'
  get 'profile', to:'main#profile'
  post 'follow', to:'main#follow'
  get 'destroy_post', to:'main#destroy_post'
  get 'other_user',to:'main#other_user'
  post 'like/:post_id',to:'main#like'
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: %i[ show edit update destroy ]

  # GET /likes or /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1 or /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes or /likes.json
  def create
    @like = Like.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to @like, notice: "Like was successfully created." }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1 or /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: "Like was successfully updated." }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1 or /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: "Like was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def like_params
      params.require(:like).permit(:user_id, :post_id)
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@like) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :user
    = f.association :post

  .form-actions
    = f.button :submit

app/views/likes/edit.html.haml
%h1 Editing like

= render 'form'

= link_to 'Show', @like
\|
= link_to 'Back', likes_path

app/views/likes/index.html.haml
%h1 Listing likes

%table{:class=>'display',:id=>'likes-index-table',:style=>'width:100%'}
  %thead
    %tr
      %th User
      %th Post
      %th
      %th
      %th

  %tbody
    - @likes.each do |like|
      %tr
        %td= like.user
        %td= like.post
        %td= link_to 'Show', like
        %td= link_to 'Edit', edit_like_path(like)
        %td= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Like', new_like_path

:javascript 
  $(document).ready(function() {
    $('#likes-index-table').DataTable( {
        columnDefs: [ {
            targets: [ 0 ],
            orderData: [ 0, 1 ]
        }, {
            targets: [ 1 ],
            orderData: [ 1, 0 ]
        } ]
    } );
  } );

app/views/likes/new.html.haml
%h1 New like

= render 'form'

= link_to 'Back', likes_path

app/views/likes/show.html.haml
%p#notice= notice

%p
  %b User:
  = @like.user
%p
  %b Post:
  = @like.post

= link_to 'Edit', edit_like_path(@like)
\|
= link_to 'Back', likes_path