config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :follows
  get 'main',to:"main#main"
  post 'login',to:"main#login"
  get 'logout',to:"main#logout"
  get 'register',to:"main#register"
  post 'register',to:"main#register_create"
  get 'feed',to:"main#feed"
  get 'create_post', to:"main#create_post"
  post 'create_new_post', to:"main#create_new_post"
  get 'profile/:name', to:'main#profile'
  get 'profile', to:'main#profile'
  post 'follow', to:'main#follow'
  get 'destroy_post', to:'main#destroy_post'
  get 'other_user',to:'main#other_user'
  post 'like/:post_id',to:'main#like'
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow, only: %i[ show edit update destroy ]

  # GET /follows or /follows.json
  def index
    @follows = Follow.all
  end

  # GET /follows/1 or /follows/1.json
  def show
  end

  # GET /follows/new
  def new
    @follow = Follow.new
  end

  # GET /follows/1/edit
  def edit
  end

  # POST /follows or /follows.json
  def create
    @follow = Follow.new(follow_params)

    respond_to do |format|
      if @follow.save
        format.html { redirect_to @follow, notice: "Follow was successfully created." }
        format.json { render :show, status: :created, location: @follow }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /follows/1 or /follows/1.json
  def update
    respond_to do |format|
      if @follow.update(follow_params)
        format.html { redirect_to @follow, notice: "Follow was successfully updated." }
        format.json { render :show, status: :ok, location: @follow }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1 or /follows/1.json
  def destroy
    @follow.destroy
    respond_to do |format|
      format.html { redirect_to follows_url, notice: "Follow was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow
      @follow = Follow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def follow_params
      params.require(:follow).permit(:follower_id, :followee_id)
    end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@follow) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :follower
    = f.association :followee

  .form-actions
    = f.button :submit

app/views/follows/edit.html.haml
%h1 Editing follow

= render 'form'

= link_to 'Show', @follow
\|
= link_to 'Back', follows_path

app/views/follows/index.html.haml
%h1 Listing follows

%table{:class=>'display',:id=>'follows-index-table',:style=>'width:100%'}
  %thead
    %tr
      %th Follower
      %th Followee
      %th
      %th
      %th

  %tbody
    - @follows.each do |follow|
      %tr
        %td= follow.follower.id
        %td= follow.followee.id
        %td= link_to 'Show', follow
        %td= link_to 'Edit', edit_follow_path(follow)
        %td= link_to 'Destroy', follow, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Follow', new_follow_path

:javascript 
  $(document).ready(function() {
    $('#follows-index-table').DataTable( {
        columnDefs: [ {
            targets: [ 0 ],
            orderData: [ 0, 1 ]
        }, {
            targets: [ 1 ],
            orderData: [ 1, 0 ]
        } ]
    } );
  } );

app/views/follows/new.html.haml
%h1 New follow

= render 'form'

= link_to 'Back', follows_path

app/views/follows/show.html.haml
%p#notice= notice

%p
  %b Follower:
  = @follow.follower
%p
  %b Followee:
  = @follow.followee

= link_to 'Edit', edit_follow_path(@follow)
\|
= link_to 'Back', follows_path